sendgridlabs/go-kinesis

examples/example.go, kinesis-cli/kinesis-cli.go, kinesis.go, kinesis_test.go
This change allows to pass in a IAM token using the Auth object
instead of passing access key id and secret key params directly.
See #19
=> Change the constructor to use Auth

kinesis.go, kinesis_test.go
This adds all missing regions that support Kinesis at the moment
(see http://docs.aws.amazon.com/general/latest/gr/rande.html#ak_region)
and additionally applies constant numbering.
=> Add missing regions and constant numbering

client.go, client_test.go, kinesis-cli/kinesis-cli.go
In order to emulate the behavior of various AWS SDKs, we should fetch auth
credentials from multiple sources. With this patch, the client will attempt
to fetch credentials from the environment and also attempt to get them from
the metadata server (if they dont exist in the environment).
Also riding on this patch are:
1. Tweaks/edit/standardize description string of some functions
2. Prettify some text that the kinesis-cli program outputs when keys are missing
=> Kinesis auth object should fetch creds from metadata server.

client.go, kinesis-cli/kinesis-cli.go
I am not a golang expert, but after this fix I could successfully use `NewAuth()` and it took variables from env as I expected.
I am open for proposals how to improve it.
=> Fix NewAuth()

examples/example.go
http://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html
Note that GetRecords won't return any data when it throws an exception. For this reason, we recommend that you wait one second between calls to GetRecords; however, it's possible that the application will get exceptions for longer than 1 second.
=> handle kinesis rate-limiting in example.go

examples/example.go
Just a small change to the example.
=> Used the kinesis.NewAuth method to ensure env vars are retrieved.

kinesis.go
This refines a change I made in e77cc7e.
=> Improve error message when JSON messages r empty

kinesis.go
Populate the Code field of the json errors so that upstream decisions can be made based on the AWS error class
=> set Error.Code with the aws json error type

kinesis.go
Hey @le0pard , sorry about that. I hadn't thoroughly tested the code previously and accidentally left out the version. Leaving out the version previously produces a 400 error. 
I also had another idea and wonder what you might think about a slight refactor on how the Auth configuration and the Client is handled. I want to propose decoupling the Client's creation to be in a separate constructor than the Kinesis struct. If you're open to that, I could go ahead and try to work on that and get a pull request up for that. It probably won't be backwards compatible too, so a strategy may be needed.
=> adding version to avoid 400 error

auth.go, auth_test.go, client.go, examples/example.go, kinesis-cli/kinesis-cli.go, kinesis.go, kinesis_test.go
Hey @le0pard ,
Here is the other refactor for decoupling out the construction of the client. Please **don't merge** this yet. I am hoping to manually test that this refactor and the previous refactor works. I'll let you know when this is ready :). Thanks again!
=> Refactor to decouple kinesis and the client

.travis.yml, README.md, batchproducer/batchproducer.go, batchproducer/batchproducer_test.go
I need this for a project of mine, and it seemed like it belonged in this library rather than in my application code.
The batch producer:
* Has a single goroutine running in the background
* Uses a channel for buffering and backpressure
* Flushes batches either when a specified batch size is in the buffer or when an optional specified interval occurs
* Accepts a StatReceiver and will regularly send stats to it
* Will retry when HTTP errors occur or are received
* Will retry individual records that fail
The retry behavior in particular is important because Kinesis sometimes returns 500 responses to valid
requests, and [AWS considers this normal](https://forums.aws.amazon.com/thread.jspa?messageID=531831).
For more details see the godoc comments.
Coverage: 96%
We (Timehop) have been using …
=> Add a retrying background batch producer

kinesis-cli/kinesis-cli.go
Fix broken kinesis-cli. kinesis-cli was breaking because it was ignoring the AWS_REGION environment variable.
=> kinesis-cli now uses the region from the environment

.travis.yml, batchproducer/batchproducer.go, batchproducer/batchproducer_test.go
The batchproducer imports were referencing "timehop" instead of the official release from "sendgridlabs". 
This resulted in my local machine failing to compile w/ the library. 
I am not sure if this is the proper way to handle packages in go and accounting for developers working w/ forks. Any tips would be appreciated if something is wrong.
=> #43: Batchproducer imports should use sendgridlabs instead of timehop

auth.go, auth_test.go
Added support for getting the access keys from the following environment variables:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
=> Fix #45: Add support for other AWS key env var names.

batchproducer/batchproducer.go, batchproducer/batchproducer_test.go
When the buffer is full and 1+ records fail, the attempt to re-enqueue the failed record(s) can block the main background goroutine, essentially deadlocking the entire BatchProducer.
Unfortunately I don’t have time to add a test right now. I’m _fairly_ certain that this should fix the bug, but this fix _might_ end up creating too many goroutines.
The whole package should probably be refactored to use a deque as the buffer, rather than a channel, so that failed records can be re-enqueued back at the head of the queue, so as to preserve ordering, or at least disrupt it less — which is important with Kinesis. In that case (with a deck), we could have one dedicated goroutine managing the deque (accepting new records via a channel and returning records via a channel), discrete and independent …
=> Quick band-aid to fix a deadlock bug

batchproducer/batchproducer.go
Hi, I'm using this library and the only way I could get it to integrate with our custom logging library was to make batchproducer take an interface instead of the log.Logger instance. The interface is only one method Printf(format string, ...args interface{}) which log.Logger satisfies. This allows me to add some custom formatting around the logs the library already outputs.
=> modify batchproducer to take an interface for logging

kinesis.go
Unfortunately the change in #53 was not correct - this value is a float, not an `int`. I was misled by the docs phrasing it this way:
> The timestamp has millisecond precision.
This seems to mean that it's a second, with the three decimal points representing the milliseconds.
I assume the reason it was still passing tests is that `kinesalite` doesn't set the value at all, so it wasn't failing?
=> [BUG] GetRecordsRecords: ApproximateArrivalTimestamp is float, not int

auth.go, auth_test.go
The AWS security token ought to be optional when the AWS Access Key ID and Secret Access Key environment variables are both set; instead, the security token is always required.
This PR makes the security-token optional when the AWS Access Key ID and Secret Access Key environment variables are set and non-empty.
Fixes #61
=> Fix issue #61 by making AWS security token optional

.travis.yml, README.md, auth.go, auth_assumerole.go, auth_cachedmutexedwarmedup.go, auth_metadata.go, auth_static.go, auth_test.go, client.go, sign.go, sign_test.go
We'd like to be able to use our IAM instance profile to assume a role (in another account) and use that to communicate with Kinesis.
This PR changes the interface for `Auth` to only needing to a set of credentials that can be used together for signing. By returning this as one object it means the `Auth` implementation can be responsible for ensuring the credentials are fresh enough for us if they are ones that expire.
We are now able to assume an STS role as follows in our code:
```golang
func NewKinesisProducer(options KinesisOptions) (batchproducer.Producer, error) {
var err error
var kinAuth kinesis.Auth
if options.AWSAccessKey == "" {
kinAuth, err = kinesis.NewAuthFromMetadata()
if err != nil {
return nil, err
}
} else {
kinAuth = kinesis.NewAuth(options.AWSAccessKey, …
```
=> Refactor auth component, add ability to use STS to assume role

examples/example.go
Now if I run example.go file, i will get unexpected errors like: 
`CreateStream ERROR: Post https://kinesis..amazonaws.com: dial tcp: lookup kinesis..amazonaws.com: no such host
ListStreams: <nil>
DescribeStream: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x64d473]
goroutine 1 [running]:
main.main()
/home/anatoliy/go/src/github.com/triggermesh/sources/awskinesis/main.go:47 +0x4c3
exit status 2
`
This PR fixes these errors, since there is a note that we should set up env var for region, in fact it is never used in the code. When I add it, everything worked. So, I think you need to include that in the code so that future users would not spend their time figuring out the error.
=> Fix example. Include region to kinesis.New, so code properly runs

kinesis.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
=> Fix function comments based on best practices from Effective Go
